### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by superp** [paa001/atom-html2slim#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [html2slim](https://github.com/paa001/atom-html2slim) package, v0.2.2
### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At /Volumes/Data/superp/.atom/packages/html2slim/lib/html2slim.coffee:18

TypeError: Cannot read property 'path' of null
    at Object.module.exports.Html2slim.convert (/Volumes/Data/superp/.atom/packages/html2slim/lib/html2slim.coffee:18:34)
    at atom-workspace.subscriptions.add.atom.commands.add.html2slim:convert (/Volumes/Data/superp/.atom/packages/html2slim/lib/html2slim.coffee:11:85)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -1:17.5.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -1:17 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -1:17 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -1:15.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:52.4.0 html2slim:convert (atom-text-editor.editor.is-focused)
     -0:31.4.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -0:28.6.0 core:undo (atom-text-editor.editor.is-focused)
     -0:27 core:cut (atom-text-editor.editor.is-focused)
     -0:25.7.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -0:25 core:save (atom-text-editor.editor.is-focused)
     -0:21.3.0 html2slim:convert (atom-text-editor.editor.is-focused)
     -0:10.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:10.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:09.2.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:08.0 core:paste (atom-text-editor.editor.is-focused)
     -0:01.7.0 html2slim:convert (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "rails-transporter",
      "ruby-test",
      "rubocop-auto-correct",
      "linter-rubocop"
    ],
    "themes": [
      "atom-light-ui",
      "railscasts-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
html2slim, v0.2.2
linter, v1.11.3
linter-ruby, v1.2.1
railscasts-theme, v1.4.0
ruby-slim, v0.2.0

# Dev
No dev packages
```

**Comment by paa001** [comment]
Do you make it with saved file? Convert can make only with saved file.
