### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addError' of undefined

### ISSUE THREAD

**Issue by 23tux** [paa001/atom-html2slim#4]
I would love to use your html2slim wrapper, but unfortunately, it throws an error.
1. Press Ctrl-P to bring up the command list
2. Search for html2slim
3. Enter

Nothing happens, just the error is thrown.

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [html2slim](https://github.com/paa001/atom-html2slim) package, v0.4.0
### Stack Trace

Uncaught TypeError: Cannot read property 'addError' of undefined

```
At /Users/user1/.atom/packages/html2slim/lib/html2slim.coffee:34

TypeError: Cannot read property 'addError' of undefined
    at /Users/user1/.atom/packages/html2slim/lib/html2slim.coffee:34:35
    at ChildProcess.exithandler (child_process.js:221:5)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```
### Commands

```
     -0:17.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.compact-tab-bar.panel-shadows.panel-contrast.compact-tree-view.theme-atom-material-syntax-dark.theme-atom-material-ui)
     -0:03.2.0 core:close (div.panels-item)
     -0:01.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 html2slim:convert (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "linter-rubocop",
      "ruby-slim"
    ],
    "followSymlinks": false,
    "ignoredNames": [
      ".DS_Store",
      ".sass-cache",
      "tmp",
      ".tmp",
      "coverage",
      "bower_components",
      "node_modules",
      "solr/development",
      "solr/conf",
      "solr/test"
    ],
    "projectHome": "/Users/user1/Documents/projects",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.13 (inactive)
atom-fuzzy-grep, v0.14.0 (inactive)
atom-html-preview, v0.1.22 (active)
atom-jade, v0.3.0 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (active)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.6 (active)
coffee-porter, v0.8.1 (active)
css-color-underline, v1.0.1 (active)
cursor-history, v0.6.1 (active)
filesize, v0.4.2 (active)
git-blame, v0.4.11 (inactive)
highlight-selected, v0.11.2 (active)
html2slim, v0.4.0 (active)
language-docker, v1.1.7 (active)
language-rspec, v0.5.0 (active)
language-slim, v0.5.0 (active)
linter, v1.11.16 (active)
linter-rubocop, v0.5.0 (inactive)
markdown-writer, v2.6.1 (inactive)
minimap, v4.25.0 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-color-highlight, v4.1.4 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-selection, v4.4.0 (active)
monokai, v0.18.0 (inactive)
rspec, v0.3.2 (inactive)
rspec-snippets, v0.4.0 (active)
rubocop-auto-correct, v1.5.1 (inactive)
ruby-slim, v0.2.0 (inactive)
ruby-syntax-replacer, v0.5.1 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
Stylus, v3.0.0 (active)
Sublime-Style-Column-Selection, v1.7.2 (active)
tablr, v1.5.3 (active)
webbox-color, v0.5.9 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by edvardm** [comment]
Did you install the required gem? `gem install html2slim`

**Comment by paa001** [comment]
I fixed it. Sorry for long long time
